server:
  port: 8888

mybatis:
  type-aliases-package: com.jie.model

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    name: myLog.log
